### ISSUE TITLE
Ability to supress printing per-test outcome

### ISSUE THREAD

**Issue by untitaker** [LukasKalbertodt/libtest-mimic#10]
I use this crate to generate roughly 20k testcases. When I run my testsuite I can add `> /dev/null` to shave 500ms off of my 3.2s test runtime.

I want to be able to stop printing one line per test output, and rather either:

1. print one dot per passing testcase (and batch/buffer the printing of dots in large batches) -- this is what rustc-test (fork of std test) appears to do in case there are many testcases: https://github.com/servo/rustc-test
2. customize on the `Test` struct, or via `Arguments`, what kind of output I want for this testfile/item.

hope that makes sense

**Comment by LukasKalbertodt** [comment]
Hi and sorry for the late reply. This crate, like the built-in test harness, supports command line arguments. One of those is `--quiet`, which does exactly what you ask for: print one dot per test. You would usually enable it like so: `cargo test -- --quiet`. Note that this passes the argument to the test runner, not `cargo`.

Does that solve your problem?

**Comment by untitaker** [comment]
Ah yeah, I wasn't aware of that flag. The default test harness appears to default to `--quiet` if there are many testcases, at least that's my impression. I am not sure how it does that.

I can solve my case by mutating Arguments though, so that's default behavior, thanks!
