### ISSUE TITLE
Incompatible with IntelliJ Rust

### ISSUE THREAD

**Issue by Dinnerbone** [LukasKalbertodt/libtest-mimic#25]
When using [IntelliJ Rust](https://www.jetbrains.com/rust/), `cargo test` is specialcased to add extra arguments to allow the IDE to parse the results. Unfortunately, these arguments aren't supported and so you can't run tests from inside the IDE if using libtest-mimic.

When running `cargo test` it actually adds: `--format=json -Z unstable-options --show-output`

- `--format=json` is tracked by #1
- `-Z unstable-options` Is used to enable `--format=json`
- `--show-output` perhaps we should also just do nothing, since that's the current behaviour I believe?

Libtest `--help` output says:
```
    --show-output   Show captured stdout of successful tests             
-Z unstable-options Enable nightly-only flags:                           
                    unstable-options = Allow use of experimental features
```

**Comment by LukasKalbertodt** [comment]
This should be fixed by #35 and 70cdc55ee50df8325d11f5e2cbe53c6bf74d375d. If there are still problems, let me know.
