### ISSUE TITLE
feature request: Add timeout support

### ISSUE THREAD

**Issue by bwidawsk** [LukasKalbertodt/libtest-mimic#36]
It would be useful if a test could timeout. As a start, a global timeout value would suffice. 

It seems pretty straightforward to implement. However, it may be considered ideal to have the test itself implement the timeout, which allows each test to specify their own timeout.

Thoughts?

**Comment by LukasKalbertodt** [comment]
Hi! 
I think the requested feature is not offered by `rustc --test`, right? In that case, I don't want to add it to this crate. `libtest-mimic` is actually just about offering exactly the built-in features for own test harnesses, but not more. A timeout feature could easily be added on top of this.
