### ISSUE TITLE
ExitCode logic inverted

### ISSUE THREAD

**Issue by sunshowers** [LukasKalbertodt/libtest-mimic#40]
Hi Lukas,

Thanks for addressing the ExitCode issue so quickly! Noticed that the logic looks inverted though, would be good to get another fix out soon.

https://github.com/LukasKalbertodt/libtest-mimic/blob/01aba1dd6ec60ab9e82f445b3c198efe5a415cf1/src/lib.rs#L341

**Comment by LukasKalbertodt** [comment]
And that's why one doesn't push out a new release within 15min first thing in the morning... grumble grumble

Thanks for catching this so quickly.

**Comment by LukasKalbertodt** [comment]
Fix published as 0.7.2
