### ISSUE TITLE
Use libtest-mimic to do setup and teardown?

### ISSUE THREAD

**Issue by dogweather** [LukasKalbertodt/libtest-mimic#6]
Hi, I'm wondering if mimic would help with this: when running `cargo test`:

1. A `setup` function is executed
2. All the tests are run just like `cargo test` would without mimic
3. A `teardown` function is executed

If I understand correctly, mimic helps with this ... eliminating the boilerplate when writing a custom harness?

**Comment by LukasKalbertodt** [comment]
Hi! How exactly do you think mimic would do that? We could pass a `setup` and a `teardown` function to `run_tests` but... you could also just call those two funtions before and after the call to `run_tests`. So one wouldn't gain anything by that.

Or you are talking about running `setup` before each test and `teardown` after each test. This is different, but can also already achieve easily today with mimic: in the closure `run_test` you pass to `run_tests` you can easily call those two functions. 

So I'm not sure how or if mimic can even help here :/

**Comment by dogweather** [comment]
Ok, I think I better understand what `libtest-mimic` actually delivers; everything _except_ the test runner. :-)

Yeah, I'm looking for a way to do before-all setup and before-all teardown, around the integration tests. It turns out, this is pretty hard to accomplish, and not built in. Maybe I could achieve it by calling `libtest` to do the actual test-runner work.

**Comment by LukasKalbertodt** [comment]
That might indeed work. But I really don't know stuff about how to manually run `#[test]` tests. So I guess I can't help you there :/

**Comment by LukasKalbertodt** [comment]
I think there is nothing to do here anymore. So I'm closing this for now.
