### ISSUE TITLE
Capture output by default

### ISSUE THREAD

**Issue by Ekleog** [LukasKalbertodt/libtest-mimic#9]
Hello,

To properly mimic the behavior of `libtest`, `libtest-mimic` should default to capturing the output and then displaying it only upon test failure.

TBH, I'm not yet really sure how to implement it, so before jumping into it, I wanted to check: would you be interested by such a feature? (Disclaimer: I don't know yet when I'll actually start doing it, so please read this as “in an ideal would, would you agree that libtest-mimic should have this feature?”)

Anyway, thank you for libtest-mimic! :)

**Comment by LukasKalbertodt** [comment]
Hi there!

Yes, that would be a great feature indeed. I wanted to implement it in the very beginning and checked how the actual libtest does it. Unfortunately... it's difficult. If I'm not mistaken, libtest actually uses internal `std::io` functions to temporarily change the stdout target or something like that. Have a look at [this snippet](https://github.com/rust-lang/libtest/blob/a120317c9d5f0bc4b139970b59fed2fca8fe29f5/libtest/lib.rs#L1483-L1490) (and probably the code below it. The way libtest does it only captures output emitted via `std`. If you write directly to stdout via different means, the output is not captured. This actually happens if you use `termcolor` for example.

Back when I wrote libtest-mimic I decided that it would not be feasible to implement that feature. Of course capturing output is easy when starting new processes, but one doesn't want to do that for each test. 

So: I don't think there exists a reasonable implementation that libtest-mimic can use. However, if you want to research and come up with an interesting solution, let me know!

**Comment by Ekleog** [comment]
Hmm… so on posix systems, I think using `dup2` would allow doing proper capture (first save stdout/stderr, then open pipes, dup2 the pipe inputs to stdout/stderr, write the things that must be written like information on which tests pass/fail by using the dup'd stdout/stderr, and dup2 the dup'd stdout/stderr back into place when done).

However… that would require running all tests one by one, because there's no way of knowing which thread wrote what in this scheme.

So I wonder: is the problem you're seeing with doing things the same way as libtest the fact that it doesn't capture eg. termcolor output, or the fact that io::set_print & co aren't public API?

**Comment by LukasKalbertodt** [comment]
So `io::set_print` not being public certainly means that libtest-mimic would have to implement its own solution. We can't use non-public APIs. Capturing most (but not all) stdout is better than not capturing at all. 

To be clear: I'm not saying it can't be done. I just don't really think `libtest-mimic` should contain such complex and platform-dependent implementations. I intend this to be a pretty light-weight library that just implements some simple plumbing stuff like CLI parsing and printing. The test runner is provided by the user. And in particular, the user can then still do stdout capturing if they so wish. One could even writer *another* crate that does that. I just don't think stdout capturing belongs into `libtest-mimic`, unless implementing that is really simple and platform-independent. 

Does this reasoning make sense?

**Comment by Ekleog** [comment]
It totally makes sense! I was mostly thinking of whether it makes sense to submit an RFC to make `set_print` & co public — not sure I'd have enough energy to bring that to completion, though.

**Comment by LukasKalbertodt** [comment]
I would probably not bother trying that. I think making that public would not only require consensus on the question whether std should offer that, but also some additional significant API design. So I think the chances of that happening are rather slim :/

I will close this issue for now then. If you or anyone else finds an easy way to capture output in libtest-mimic, please let us know in this issue.

**Comment by Ekleog** [comment]
Hmm yes, makes sense I guess. Thank you for your feedback!

**Comment by MatteoNardi** [comment]
> I just don't think stdout capturing belongs into `libtest-mimic`, unless implementing that is really simple and platform-independent.

How about spawning tests in different processes? 
Basically what I'm thinking of is:
- We add a custom `--spawn-processes` flag which activates this behavior
- For each test, `libtest_mimic::run` will re-execute the current process, changing the command line arguments:
  - We remove `--spawn-processes` flag
  - We set `--exact <test name>`
  - We add a `FormatSetting::Silent` which causes no extra output (Eg. no "running <x> tests" and no "test result: ...")
- If the exit code is 0, we assume the test succeded. If not, it's failed and we print the captured stdout/stderr

This would require no extra dependencies and would be cross-platform. On the down side, it's wasteful to spawn so many processes and we would have to properly document this re-execution thing.
Alternatively, we could use [procspawn](https://github.com/mitsuhiko/procspawn). That would allow use to re-use a process pool, but would be slightly more complex and I'm not sure it works on windows. 

For context, in [pulsar](https://github.com/Exein-io/pulsar) we have a [test-suite](https://github.com/Exein-io/pulsar/tree/main/test-suite) which needs to be run with admin privileges, so we decided to make a separate binary. `libtest-mimic` proved really useful for the task. Currently, our [test runner](https://github.com/Exein-io/pulsar/blob/main/test-suite/src/main.rs) has to (1) install a custom logger for intercepting output, (2) replace panic hook, (3) send tests to a different tokio-compatibile executor task.
I was wondering if we could simplify our code and contribute back.

**Comment by LukasKalbertodt** [comment]
I'm pretty sure that approach would work and I have even considered doing that. But you already listed the main disadvantages and I don't think it's a good route to go for this library. As I wrote above:

> Of course capturing output is easy when starting new processes, but one doesn't want to do that for each test.

 I understand that not having stdout captured is annoying in quite some use cases, but I don't see a good way that would fit nicely in libtest-mimic. 

Something I could imagine is that some other library could offer this "capture stdout of this process" functionality; and libtest-mimic could get a new cargo feature that would enable using that library. I'm pretty sure the library would have to use those internal std functions, and thus would come with a "only use for development, might break at any moment" warning. But if libtest-mimic just refers to that warning as description of the crate feature, I think that would be fine.

---

> For context, in [pulsar](https://github.com/Exein-io/pulsar) we have a [test-suite](https://github.com/Exein-io/pulsar/tree/main/test-suite) which needs to be run with admin privileges, so we decided to make a separate binary. `libtest-mimic` proved really useful for the task. Currently, our [test runner](https://github.com/Exein-io/pulsar/blob/main/test-suite/src/main.rs) has to (1) install a custom logger for intercepting output, (2) replace panic hook, (3) send tests to a different tokio-compatibile executor task.
> I was wondering if we could simplify our code and contribute back.

That's interesting, thanks for letting me know! If I understand correctly, only (1) and (2) have to do with this issue, right? (3) is to allow running async tests, I assume? Maybe open a separate issue for that one.

But thanks for bringing panic message output to my attention -- I haven't really thought about it. I just checked and yes, the rustc test suite does hide panic outputs. So I guess libtest mimic should do that too? That's a lot easier than hiding/capturing all stdout output, right? You only need to overwrite the panic hook, correct? But the panic hook is set globally for the whole process... mh. So panics within libtest-mimic would be hidden as well? Mhhhh. Maybe one has to think about it for another minute.

**Comment by MatteoNardi** [comment]
> Something I could imagine is that some other library could offer this "capture stdout of this process" functionality; and libtest-mimic could get a new cargo feature that would enable using that library. I'm pretty sure the library would have to use those internal std functions, and thus would come with a "only use for development, might break at any moment" warning. But if libtest-mimic just refers to that warning as description of the crate feature, I think that would be fine.

Users enabling that libtest-mimic feature will need a nightly compiler. Unfortunate, but this could still be useful when all other workarounds fail.

> That's interesting, thanks for letting me know! If I understand correctly, only (1) and (2) have to do with this issue, right? (3) is to allow running async tests, I assume? Maybe open a separate issue for that one.

Yes. I'm not sure it makes sense to add extra features to the library just for that though. After all, you can just spawn a tokio Runtime in each test.

> But thanks for bringing panic message output to my attention

Yeah, we could work on that. I'll give it a try and see if I can come up with a clean solution.
As a side note: the current `catch_unwind` won't print the line number of the panic, while the panic hook would have that info.

It's kind of confusing we'd only catch one kind of output, but many test suites don't write much to stdout apart from that. On top of this, if we supplied a custom log implementation, I think we'd cover most use-cases for wanting to capture output. I'll open up an issue for that.

**Comment by MatteoNardi** [comment]
> But the panic hook is set globally for the whole process...

Follow-up to my previous message: the panic hook and logger are both global resources of the whole process. They do allow us to intercept messages, but I see no way to associate them to the correct test (unless we run only one at the time, which would be super slow)

I was planning to copy the standard library approach for `set_output_capture`, basically a [thread local buffer](https://github.com/rust-lang/rust/blob/1dda298ad39a64e019a3511139c5b13ac0a18e54/library/std/src/io/stdio.rs#L21). Unfortunately this works because it [gets cloned](https://github.com/rust-lang/rust/blob/1dda298ad39a64e019a3511139c5b13ac0a18e54/library/std/src/thread/mod.rs#L541) when a new (standard library) thread is spawned. We can't do that.

**Comment by Kinrany** [comment]
Could it be a single process for all tests instead of one per test?

**Comment by MatteoNardi** [comment]
> Could it be a single process for all tests instead of one per test?

I think spawning a single separate process which runs all the tests would allow us to capture output, but we wouldn't know how to associate the output to each test. This is the same blocker I hit when intercepting log messages and the panic hook, see my last comment.

**Comment by DanielJoyce** [comment]
Well set_print and set_panic no longer exist so libtest must be using something else.

**Comment by DanielJoyce** [comment]
it looks like this is the new testing framework, and run_test_inner no longer uses set_print, but uses the spawn trick people were talking about.

https://github.com/rust-lang/rust/blob/4c83bd03a9d94af35c97a6b8b595d40e291af84a/library/test/src/lib.rs#L563

**Comment by ISSOtm** [comment]
Actually, `set_print` seems to have been renamed to [`set_output_capture`](https://github.com/rust-lang/rust/blob/31026b7fe3e510a646eddeda838d1f0859f892e7/library/test/src/lib.rs#L644).

Too bad, it would be nicer not to have duplicate output in the logs (particularly if the test panics; in my case, `snapbox`'s functions panic on failure instead of returning errors).
